"""
Groq LLM Text-to-SQL Service for InsightAI.
Integrates the official Groq SDK for high-performance, read-only DuckDB SQL generation.
Enforces dynamic schema context injection, prompt engineering for raw SQL output,
and graceful rate limit retry handling.
"""

import asyncio
import logging
import os
import re
from typing import Any, Dict, List, Optional

from groq import APIConnectionError, APIError, AsyncGroq, RateLimitError

from app.core.config import settings
from app.schemas.dataset import DatasetSchema

logger = logging.getLogger("insightai.llm_service")


def clean_llm_sql_response(raw_response: str) -> str:
    """
    Strips markdown code fences, leading/trailing whitespace, and trailing semicolons
    from LLM text generation responses.
    """
    if not raw_response:
        return ""

    cleaned = raw_response.strip()

    # Remove markdown codeblock backticks if present (```sql ... ```)
    pattern = r"^```(?:sql)?\s*(.*?)\s*```$"
    match = re.search(pattern, cleaned, re.DOTALL | re.IGNORECASE)
    if match:
        cleaned = match.group(1).strip()
    else:
        # Fallback manual line filtering for multiline backticks
        lines = cleaned.splitlines()
        if lines and lines[0].strip().startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip().startswith("```"):
            lines = lines[:-1]
        cleaned = "\n".join(lines).strip()

    return cleaned.rstrip(";").strip()


class LLMService:
    """Enterprise LLM Service using official Groq SDK for Text-to-SQL translation."""

    @classmethod
    def format_schema_context(cls, schema: DatasetSchema, table_name: str = "dataset") -> str:
        """
        Formats DuckDB dataset schema metadata (table name, column names, data types, sample values)
        into a clean context block for dynamic LLM prompt injection.
        """
        lines = [
            f"Table Name: '{table_name}'",
            f"Total Rows: {schema.total_rows}",
            f"Total Columns: {schema.total_columns}",
            "Schema Structure (Column Name | Data Type | Sample Values):",
        ]
        for col in schema.columns:
            samples = ", ".join(repr(v) for v in col.sample_values[:3]) if col.sample_values else "N/A"
            lines.append(f"  - {col.name} ({col.data_type}) -> Samples: [{samples}]")
        return "\n".join(lines)

    @classmethod
    async def generate_sql_from_natural_language(
        cls,
        question: str,
        schema: DatasetSchema,
        table_name: str = "dataset",
        model: Optional[str] = None,
        max_retries: int = 3,
    ) -> str:
        """
        Translates a natural language question into a DuckDB SQL query using Groq API.

        Args:
            question: Plain-English question from the user.
            schema: Dataset schema metadata fetched from DuckDB.
            table_name: DuckDB table view name to query.
            model: Optional Groq model identifier override.
            max_retries: Maximum rate limit retry attempts.

        Returns:
            Raw SQL query string generated by Groq LLM.

        Raises:
            ValueError: If API key missing, empty response, or rate limit retries exhausted.
        """
        api_key = settings.GROQ_API_KEY or os.getenv("GROQ_API_KEY")
        if not api_key:
            raise ValueError(
                "Groq API Key is not configured. Please set GROQ_API_KEY environment variable or config setting."
            )

        target_model = model or settings.GROQ_MODEL
        schema_context = cls.format_schema_context(schema, table_name)

        system_prompt = (
            "You are an Elite Enterprise Backend Architect and SQL Data Engineer specializing in DuckDB OLAP.\n"
            "Your sole function is to convert user natural language questions into valid, highly optimized DuckDB SQL queries.\n\n"
            "STRICT CONSTRAINTS:\n"
            "1. Output ONLY raw DuckDB SQL. Do NOT wrap in markdown syntax (NO ```sql or ``` fences). Do NOT add explanations, titles, or conversational filler.\n"
            "2. Generate strictly read-only SELECT or WITH (CTE) statements targeting the table provided in the schema.\n"
            "3. Do NOT use DROP, DELETE, UPDATE, INSERT, ALTER, TRUNCATE, or DDL/DML statements.\n"
            "4. Only reference columns defined in the provided schema context. Use exact column names.\n"
            "5. For string comparisons, use case-insensitive matching if appropriate (e.g., LOWER(col) = LOWER('val')).\n"
            "6. Always limit results to a reasonable count (e.g., LIMIT 100) unless an explicit aggregation (COUNT, SUM, AVG) is requested."
        )

        user_prompt = (
            f"--- DATABASE SCHEMA CONTEXT ---\n"
            f"{schema_context}\n\n"
            f"--- USER QUESTION ---\n"
            f"{question}\n\n"
            f"Generate DuckDB SQL Query:"
        )

        client = AsyncGroq(api_key=api_key)

        for attempt in range(1, max_retries + 1):
            try:
                logger.info(f"Dispatching Text-to-SQL request to Groq API (Model: {target_model}, Attempt: {attempt})")
                response = await client.chat.completions.create(
                    model=target_model,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt},
                    ],
                    temperature=0.1,
                    max_tokens=1024,
                )

                raw_content = response.choices[0].message.content or ""
                cleaned_sql = clean_llm_sql_response(raw_content)

                if not cleaned_sql:
                    raise ValueError("Groq LLM returned an empty response string.")

                logger.info(f"Groq Text-to-SQL successfully generated query: {cleaned_sql}")
                return cleaned_sql

            except RateLimitError as rle:
                logger.warning(f"Groq API Rate Limit reached on attempt {attempt}/{max_retries}: {rle}")
                if attempt == max_retries:
                    raise ValueError(f"Groq API rate limit exceeded after {max_retries} attempts. Please try again later.")
                await asyncio.sleep(2 ** attempt)

            except (APIConnectionError, APIError) as api_err:
                logger.error(f"Groq API Error on attempt {attempt}/{max_retries}: {api_err}")
                if attempt == max_retries:
                    raise ValueError(f"Groq API service error: {str(api_err)}")
                await asyncio.sleep(1)

            except Exception as exc:
                logger.error(f"Unexpected error in LLM service: {exc}", exc_info=True)
                raise exc

        raise ValueError("Failed to generate SQL from LLM service.")
