"""
Strict SQL AST Security Validator for InsightAI using SQLGlot.
Parses LLM-generated DuckDB SQL strings into Abstract Syntax Trees (ASTs)
and enforces read-only SELECT permissions.
"""

import logging
from typing import List, Tuple, Type
import sqlglot
from sqlglot import exp
from sqlglot.errors import ParseError

logger = logging.getLogger("insightai.sql_validator")

# Explicit list of forbidden SQLGlot AST Node types for DDL/DML mutation safety
FORBIDDEN_AST_NODES: Tuple[Type[exp.Expression], ...] = (
    exp.Drop,
    exp.Delete,
    exp.Update,
    exp.Insert,
    exp.Alter,
    exp.Create,
    exp.Merge,
    exp.Command,
    exp.Execute,
    exp.Kill,
    exp.Pragma,
    exp.Transaction,
    exp.Commit,
    exp.Rollback,
    exp.Set,
)


def validate_sql(sql_query: str) -> str:
    """
    Parses a raw SQL query string into a DuckDB AST and enforces strict read-only safety rules.

    Args:
        sql_query: The raw SQL string generated by LLM or user.

    Returns:
        Formatted, validated DuckDB SQL query string.

    Raises:
        ValueError: If query parsing fails, contains non-SELECT operations,
                   or contains forbidden AST nodes (DROP, DELETE, UPDATE, INSERT, ALTER, TRUNCATE).
    """
    if not sql_query or not sql_query.strip():
        raise ValueError("SQL query string cannot be empty.")

    cleaned_sql = sql_query.strip().rstrip(";")

    try:
        # Parse statements using DuckDB dialect
        parsed_statements = sqlglot.parse(cleaned_sql, read="duckdb")
    except ParseError as pe:
        logger.error(f"SQLGlot parse error: {pe}")
        raise ValueError(f"Invalid DuckDB SQL syntax: {str(pe)}")
    except Exception as exc:
        logger.error(f"Unexpected error during SQL AST parsing: {exc}")
        raise ValueError(f"Failed to parse SQL query: {str(exc)}")

    statements = [stmt for stmt in parsed_statements if stmt is not None]

    if not statements:
        raise ValueError("No valid SQL statement found in input.")

    if len(statements) > 1:
        raise ValueError("Multi-statement SQL execution is strictly forbidden for security.")

    expression = statements[0]

    # Walk the entire AST tree to enforce read-only safety
    for node in expression.walk():
        if isinstance(node, FORBIDDEN_AST_NODES):
            forbidden_name = node.__class__.__name__.upper()
            raise ValueError(
                f"Unsafe SQL operation detected: '{forbidden_name}'. "
                f"Only read-only SELECT queries are permitted."
            )

    # Ensure top-level statement is a SELECT query or UNION / CTE query
    if not isinstance(expression, (exp.Select, exp.Union, exp.Subquery)):
        raise ValueError(
            f"Query statement type '{expression.__class__.__name__}' is not permitted. "
            f"Queries must be read-only SELECT statements."
        )

    formatted_sql = expression.sql(dialect="duckdb", pretty=True)
    logger.info("SQL AST validation passed successfully.")
    return formatted_sql
